package in.testpress.testpress.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANNER".
 */
public class Banner {

    private Long id;
    private String url;
    private String image;

    public Banner() {
    }

    public Banner(Long id) {
        this.id = id;
    }

    public Banner(Long id, String url, String image) {
        this.id = id;
        this.url = url;
        this.image = image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}
