package in.testpress.testpress.models;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CATEGORY".
 */
@Entity
public class Category {

    @Id
    private Long id;
    public String name;
    private String color;
    private String slug;

    @Generated(hash = 1150634039)
    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    @Generated(hash = 1792114525)
    public Category(Long id, String name, String color, String slug) {
        this.id = id;
        this.name = name;
        this.color = color;
        this.slug = slug;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

}
