package in.testpress.testpress.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import in.testpress.testpress.models.Post;
import in.testpress.testpress.models.Category;
import in.testpress.testpress.models.InstituteSettings;
import in.testpress.testpress.models.Forum;
import in.testpress.testpress.models.User;

import in.testpress.testpress.models.PostDao;
import in.testpress.testpress.models.CategoryDao;
import in.testpress.testpress.models.InstituteSettingsDao;
import in.testpress.testpress.models.ForumDao;
import in.testpress.testpress.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig instituteSettingsDaoConfig;
    private final DaoConfig forumDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PostDao postDao;
    private final CategoryDao categoryDao;
    private final InstituteSettingsDao instituteSettingsDao;
    private final ForumDao forumDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        instituteSettingsDaoConfig = daoConfigMap.get(InstituteSettingsDao.class).clone();
        instituteSettingsDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        postDao = new PostDao(postDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        instituteSettingsDao = new InstituteSettingsDao(instituteSettingsDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Post.class, postDao);
        registerDao(Category.class, categoryDao);
        registerDao(InstituteSettings.class, instituteSettingsDao);
        registerDao(Forum.class, forumDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        postDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        instituteSettingsDaoConfig.getIdentityScope().clear();
        forumDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public InstituteSettingsDao getInstituteSettingsDao() {
        return instituteSettingsDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
