package in.testpress.testpress.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import in.testpress.testpress.models.Post;
import in.testpress.testpress.models.Category;
import in.testpress.testpress.models.DBSession;

import in.testpress.testpress.models.PostDao;
import in.testpress.testpress.models.CategoryDao;
import in.testpress.testpress.models.DBSessionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig dBSessionDaoConfig;

    private final PostDao postDao;
    private final CategoryDao categoryDao;
    private final DBSessionDao dBSessionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        dBSessionDaoConfig = daoConfigMap.get(DBSessionDao.class).clone();
        dBSessionDaoConfig.initIdentityScope(type);

        postDao = new PostDao(postDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        dBSessionDao = new DBSessionDao(dBSessionDaoConfig, this);

        registerDao(Post.class, postDao);
        registerDao(Category.class, categoryDao);
        registerDao(DBSession.class, dBSessionDao);
    }
    
    public void clear() {
        postDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        dBSessionDaoConfig.getIdentityScope().clear();
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public DBSessionDao getDBSessionDao() {
        return dBSessionDao;
    }

}
