package in.testpress.testpress.models;

import in.testpress.util.IntegerList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DASHBOARD_SECTION".
 */
public class DashboardSection {

    private String slug;
    private String displayName;
    private String url;
    private String contentType;
    private String order;
    private String displayType;
    private IntegerList items;

    public DashboardSection() {
    }

    public DashboardSection(String slug) {
        this.slug = slug;
    }

    public DashboardSection(String slug, String displayName, String url, String contentType, String order, String displayType, IntegerList items) {
        this.slug = slug;
        this.displayName = displayName;
        this.url = url;
        this.contentType = contentType;
        this.order = order;
        this.displayType = displayType;
        this.items = items;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getOrder() {
        return order;
    }

    public void setOrder(String order) {
        this.order = order;
    }

    public String getDisplayType() {
        return displayType;
    }

    public void setDisplayType(String displayType) {
        this.displayType = displayType;
    }

    public IntegerList getItems() {
        return items;
    }

    public void setItems(IntegerList items) {
        this.items = items;
    }

}
