package in.testpress.testpress.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import in.testpress.testpress.models.InstituteSettings;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSTITUTE_SETTINGS".
*/
public class InstituteSettingsDao extends AbstractDao<InstituteSettings, String> {

    public static final String TABLENAME = "INSTITUTE_SETTINGS";

    /**
     * Properties of entity InstituteSettings.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property BaseUrl = new Property(0, String.class, "baseUrl", true, "BASE_URL");
        public final static Property VerificationMethod = new Property(1, String.class, "verificationMethod", false, "VERIFICATION_METHOD");
        public final static Property AllowSignup = new Property(2, Boolean.class, "allowSignup", false, "ALLOW_SIGNUP");
        public final static Property ForceStudentData = new Property(3, Boolean.class, "forceStudentData", false, "FORCE_STUDENT_DATA");
        public final static Property RemoveTpBranding = new Property(4, Boolean.class, "removeTpBranding", false, "REMOVE_TP_BRANDING");
        public final static Property Url = new Property(5, String.class, "url", false, "URL");
        public final static Property ShowGameFrontend = new Property(6, Boolean.class, "showGameFrontend", false, "SHOW_GAME_FRONTEND");
        public final static Property CoursesEnabled = new Property(7, Boolean.class, "coursesEnabled", false, "COURSES_ENABLED");
        public final static Property CoursesEnableGamification = new Property(8, Boolean.class, "coursesEnableGamification", false, "COURSES_ENABLE_GAMIFICATION");
        public final static Property CoursesLabel = new Property(9, String.class, "coursesLabel", false, "COURSES_LABEL");
        public final static Property PostsEnabled = new Property(10, Boolean.class, "postsEnabled", false, "POSTS_ENABLED");
        public final static Property PostsLabel = new Property(11, String.class, "postsLabel", false, "POSTS_LABEL");
        public final static Property StoreEnabled = new Property(12, Boolean.class, "storeEnabled", false, "STORE_ENABLED");
        public final static Property StoreLabel = new Property(13, String.class, "storeLabel", false, "STORE_LABEL");
        public final static Property DocumentsEnabled = new Property(14, Boolean.class, "documentsEnabled", false, "DOCUMENTS_ENABLED");
        public final static Property DocumentsLabel = new Property(15, String.class, "documentsLabel", false, "DOCUMENTS_LABEL");
        public final static Property ResultsEnabled = new Property(16, Boolean.class, "resultsEnabled", false, "RESULTS_ENABLED");
        public final static Property DashboardEnabled = new Property(17, Boolean.class, "dashboardEnabled", false, "DASHBOARD_ENABLED");
        public final static Property FacebookLoginEnabled = new Property(18, Boolean.class, "facebookLoginEnabled", false, "FACEBOOK_LOGIN_ENABLED");
        public final static Property GoogleLoginEnabled = new Property(19, Boolean.class, "googleLoginEnabled", false, "GOOGLE_LOGIN_ENABLED");
        public final static Property CommentsVotingEnabled = new Property(20, Boolean.class, "commentsVotingEnabled", false, "COMMENTS_VOTING_ENABLED");
    };


    public InstituteSettingsDao(DaoConfig config) {
        super(config);
    }
    
    public InstituteSettingsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSTITUTE_SETTINGS\" (" + //
                "\"BASE_URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: baseUrl
                "\"VERIFICATION_METHOD\" TEXT," + // 1: verificationMethod
                "\"ALLOW_SIGNUP\" INTEGER," + // 2: allowSignup
                "\"FORCE_STUDENT_DATA\" INTEGER," + // 3: forceStudentData
                "\"REMOVE_TP_BRANDING\" INTEGER," + // 4: removeTpBranding
                "\"URL\" TEXT," + // 5: url
                "\"SHOW_GAME_FRONTEND\" INTEGER," + // 6: showGameFrontend
                "\"COURSES_ENABLED\" INTEGER," + // 7: coursesEnabled
                "\"COURSES_ENABLE_GAMIFICATION\" INTEGER," + // 8: coursesEnableGamification
                "\"COURSES_LABEL\" TEXT," + // 9: coursesLabel
                "\"POSTS_ENABLED\" INTEGER," + // 10: postsEnabled
                "\"POSTS_LABEL\" TEXT," + // 11: postsLabel
                "\"STORE_ENABLED\" INTEGER," + // 12: storeEnabled
                "\"STORE_LABEL\" TEXT," + // 13: storeLabel
                "\"DOCUMENTS_ENABLED\" INTEGER," + // 14: documentsEnabled
                "\"DOCUMENTS_LABEL\" TEXT," + // 15: documentsLabel
                "\"RESULTS_ENABLED\" INTEGER," + // 16: resultsEnabled
                "\"DASHBOARD_ENABLED\" INTEGER," + // 17: dashboardEnabled
                "\"FACEBOOK_LOGIN_ENABLED\" INTEGER," + // 18: facebookLoginEnabled
                "\"GOOGLE_LOGIN_ENABLED\" INTEGER," + // 19: googleLoginEnabled
                "\"COMMENTS_VOTING_ENABLED\" INTEGER);"); // 20: commentsVotingEnabled
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSTITUTE_SETTINGS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, InstituteSettings entity) {
        stmt.clearBindings();
 
        String baseUrl = entity.getBaseUrl();
        if (baseUrl != null) {
            stmt.bindString(1, baseUrl);
        }
 
        String verificationMethod = entity.getVerificationMethod();
        if (verificationMethod != null) {
            stmt.bindString(2, verificationMethod);
        }
 
        Boolean allowSignup = entity.getAllowSignup();
        if (allowSignup != null) {
            stmt.bindLong(3, allowSignup ? 1L: 0L);
        }
 
        Boolean forceStudentData = entity.getForceStudentData();
        if (forceStudentData != null) {
            stmt.bindLong(4, forceStudentData ? 1L: 0L);
        }
 
        Boolean removeTpBranding = entity.getRemoveTpBranding();
        if (removeTpBranding != null) {
            stmt.bindLong(5, removeTpBranding ? 1L: 0L);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
 
        Boolean showGameFrontend = entity.getShowGameFrontend();
        if (showGameFrontend != null) {
            stmt.bindLong(7, showGameFrontend ? 1L: 0L);
        }
 
        Boolean coursesEnabled = entity.getCoursesEnabled();
        if (coursesEnabled != null) {
            stmt.bindLong(8, coursesEnabled ? 1L: 0L);
        }
 
        Boolean coursesEnableGamification = entity.getCoursesEnableGamification();
        if (coursesEnableGamification != null) {
            stmt.bindLong(9, coursesEnableGamification ? 1L: 0L);
        }
 
        String coursesLabel = entity.getCoursesLabel();
        if (coursesLabel != null) {
            stmt.bindString(10, coursesLabel);
        }
 
        Boolean postsEnabled = entity.getPostsEnabled();
        if (postsEnabled != null) {
            stmt.bindLong(11, postsEnabled ? 1L: 0L);
        }
 
        String postsLabel = entity.getPostsLabel();
        if (postsLabel != null) {
            stmt.bindString(12, postsLabel);
        }
 
        Boolean storeEnabled = entity.getStoreEnabled();
        if (storeEnabled != null) {
            stmt.bindLong(13, storeEnabled ? 1L: 0L);
        }
 
        String storeLabel = entity.getStoreLabel();
        if (storeLabel != null) {
            stmt.bindString(14, storeLabel);
        }
 
        Boolean documentsEnabled = entity.getDocumentsEnabled();
        if (documentsEnabled != null) {
            stmt.bindLong(15, documentsEnabled ? 1L: 0L);
        }
 
        String documentsLabel = entity.getDocumentsLabel();
        if (documentsLabel != null) {
            stmt.bindString(16, documentsLabel);
        }
 
        Boolean resultsEnabled = entity.getResultsEnabled();
        if (resultsEnabled != null) {
            stmt.bindLong(17, resultsEnabled ? 1L: 0L);
        }
 
        Boolean dashboardEnabled = entity.getDashboardEnabled();
        if (dashboardEnabled != null) {
            stmt.bindLong(18, dashboardEnabled ? 1L: 0L);
        }
 
        Boolean facebookLoginEnabled = entity.getFacebookLoginEnabled();
        if (facebookLoginEnabled != null) {
            stmt.bindLong(19, facebookLoginEnabled ? 1L: 0L);
        }
 
        Boolean googleLoginEnabled = entity.getGoogleLoginEnabled();
        if (googleLoginEnabled != null) {
            stmt.bindLong(20, googleLoginEnabled ? 1L: 0L);
        }
 
        Boolean commentsVotingEnabled = entity.getCommentsVotingEnabled();
        if (commentsVotingEnabled != null) {
            stmt.bindLong(21, commentsVotingEnabled ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public InstituteSettings readEntity(Cursor cursor, int offset) {
        InstituteSettings entity = new InstituteSettings( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // baseUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // verificationMethod
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // allowSignup
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // forceStudentData
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // removeTpBranding
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // url
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // showGameFrontend
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // coursesEnabled
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // coursesEnableGamification
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // coursesLabel
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // postsEnabled
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // postsLabel
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // storeEnabled
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // storeLabel
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0, // documentsEnabled
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // documentsLabel
            cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0, // resultsEnabled
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0, // dashboardEnabled
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0, // facebookLoginEnabled
            cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0, // googleLoginEnabled
            cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0 // commentsVotingEnabled
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, InstituteSettings entity, int offset) {
        entity.setBaseUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setVerificationMethod(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAllowSignup(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setForceStudentData(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setRemoveTpBranding(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setShowGameFrontend(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setCoursesEnabled(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setCoursesEnableGamification(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setCoursesLabel(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPostsEnabled(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setPostsLabel(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStoreEnabled(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setStoreLabel(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDocumentsEnabled(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0);
        entity.setDocumentsLabel(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setResultsEnabled(cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0);
        entity.setDashboardEnabled(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
        entity.setFacebookLoginEnabled(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
        entity.setGoogleLoginEnabled(cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0);
        entity.setCommentsVotingEnabled(cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(InstituteSettings entity, long rowId) {
        return entity.getBaseUrl();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(InstituteSettings entity) {
        if(entity != null) {
            return entity.getBaseUrl();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
