package in.testpress.testpress.models;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import in.testpress.testpress.models.LeaderboardItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEADERBOARD_ITEM".
*/
public class LeaderboardItemDao extends AbstractDao<LeaderboardItem, Long> {

    public static final String TABLENAME = "LEADERBOARD_ITEM";

    /**
     * Properties of entity LeaderboardItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property TrophiesCount = new Property(1, String.class, "trophiesCount", false, "TROPHIES_COUNT");
        public final static Property Difference = new Property(2, Integer.class, "difference", false, "DIFFERENCE");
        public final static Property Category = new Property(3, Integer.class, "category", false, "CATEGORY");
        public final static Property UserId = new Property(4, Long.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;


    public LeaderboardItemDao(DaoConfig config) {
        super(config);
    }
    
    public LeaderboardItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEADERBOARD_ITEM\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TROPHIES_COUNT\" TEXT," + // 1: trophiesCount
                "\"DIFFERENCE\" INTEGER," + // 2: difference
                "\"CATEGORY\" INTEGER," + // 3: category
                "\"USER_ID\" INTEGER);"); // 4: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEADERBOARD_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LeaderboardItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trophiesCount = entity.getTrophiesCount();
        if (trophiesCount != null) {
            stmt.bindString(2, trophiesCount);
        }
 
        Integer difference = entity.getDifference();
        if (difference != null) {
            stmt.bindLong(3, difference);
        }
 
        Integer category = entity.getCategory();
        if (category != null) {
            stmt.bindLong(4, category);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(5, userId);
        }
    }

    @Override
    protected void attachEntity(LeaderboardItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LeaderboardItem readEntity(Cursor cursor, int offset) {
        LeaderboardItem entity = new LeaderboardItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // trophiesCount
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // difference
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // category
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LeaderboardItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrophiesCount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDifference(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCategory(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUserId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LeaderboardItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LeaderboardItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM LEADERBOARD_ITEM T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LeaderboardItem loadCurrentDeep(Cursor cursor, boolean lock) {
        LeaderboardItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public LeaderboardItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LeaderboardItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LeaderboardItem> list = new ArrayList<LeaderboardItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LeaderboardItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LeaderboardItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
