package in.testpress.testpress.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RSS_ITEM".
 */
public class RssItem {

    private Long id;
    private String title;
    private String link;
    private String image;
    private Long publishDate;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RssItem() {
    }

    public RssItem(Long id) {
        this.id = id;
    }

    public RssItem(Long id, String title, String link, String image, Long publishDate, String description) {
        this.id = id;
        this.title = title;
        this.link = link;
        this.image = image;
        this.publishDate = publishDate;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(Long publishDate) {
        this.publishDate = publishDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
