package in.testpress.testpress.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SESSION".
 */
public class Session {

    private Long id;
    private Long created;
    private String state;
    private String latestPostReceived;
    private String oldestPostReceived;
    private String last_synced_date;

    public Session() {
    }

    public Session(Long id) {
        this.id = id;
    }

    public Session(Long id, Long created, String state, String latestPostReceived, String oldestPostReceived, String last_synced_date) {
        this.id = id;
        this.created = created;
        this.state = state;
        this.latestPostReceived = latestPostReceived;
        this.oldestPostReceived = oldestPostReceived;
        this.last_synced_date = last_synced_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getLatestPostReceived() {
        return latestPostReceived;
    }

    public void setLatestPostReceived(String latestPostReceived) {
        this.latestPostReceived = latestPostReceived;
    }

    public String getOldestPostReceived() {
        return oldestPostReceived;
    }

    public void setOldestPostReceived(String oldestPostReceived) {
        this.oldestPostReceived = oldestPostReceived;
    }

    public String getLast_synced_date() {
        return last_synced_date;
    }

    public void setLast_synced_date(String last_synced_date) {
        this.last_synced_date = last_synced_date;
    }

}
