package in.testpress.testpress.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_STAT_DATES".
 */
public class UserStatDates {

    private String monthStart;
    private String monthEnd;
    private String yearStart;
    private String yearEnd;
    private String weekStart;
    private String weekEnd;

    public UserStatDates() {
    }

    public UserStatDates(String monthStart, String monthEnd, String yearStart, String yearEnd, String weekStart, String weekEnd) {
        this.monthStart = monthStart;
        this.monthEnd = monthEnd;
        this.yearStart = yearStart;
        this.yearEnd = yearEnd;
        this.weekStart = weekStart;
        this.weekEnd = weekEnd;
    }

    public String getMonthStart() {
        return monthStart;
    }

    public void setMonthStart(String monthStart) {
        this.monthStart = monthStart;
    }

    public String getMonthEnd() {
        return monthEnd;
    }

    public void setMonthEnd(String monthEnd) {
        this.monthEnd = monthEnd;
    }

    public String getYearStart() {
        return yearStart;
    }

    public void setYearStart(String yearStart) {
        this.yearStart = yearStart;
    }

    public String getYearEnd() {
        return yearEnd;
    }

    public void setYearEnd(String yearEnd) {
        this.yearEnd = yearEnd;
    }

    public String getWeekStart() {
        return weekStart;
    }

    public void setWeekStart(String weekStart) {
        this.weekStart = weekStart;
    }

    public String getWeekEnd() {
        return weekEnd;
    }

    public void setWeekEnd(String weekEnd) {
        this.weekEnd = weekEnd;
    }

}
