package in.testpress.testpress.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_STATS".
 */
public class UserStats {

    private Long id;
    private String dateFrom;
    private Integer attemptsCount;
    private Integer attemptsCountDifference;
    private String videoWatchedDuration;
    private String videoWatchedDurationDifference;
    private String category;

    public UserStats() {
    }

    public UserStats(Long id) {
        this.id = id;
    }

    public UserStats(Long id, String dateFrom, Integer attemptsCount, Integer attemptsCountDifference, String videoWatchedDuration, String videoWatchedDurationDifference, String category) {
        this.id = id;
        this.dateFrom = dateFrom;
        this.attemptsCount = attemptsCount;
        this.attemptsCountDifference = attemptsCountDifference;
        this.videoWatchedDuration = videoWatchedDuration;
        this.videoWatchedDurationDifference = videoWatchedDurationDifference;
        this.category = category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(String dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Integer getAttemptsCount() {
        return attemptsCount;
    }

    public void setAttemptsCount(Integer attemptsCount) {
        this.attemptsCount = attemptsCount;
    }

    public Integer getAttemptsCountDifference() {
        return attemptsCountDifference;
    }

    public void setAttemptsCountDifference(Integer attemptsCountDifference) {
        this.attemptsCountDifference = attemptsCountDifference;
    }

    public String getVideoWatchedDuration() {
        return videoWatchedDuration;
    }

    public void setVideoWatchedDuration(String videoWatchedDuration) {
        this.videoWatchedDuration = videoWatchedDuration;
    }

    public String getVideoWatchedDurationDifference() {
        return videoWatchedDurationDifference;
    }

    public void setVideoWatchedDurationDifference(String videoWatchedDurationDifference) {
        this.videoWatchedDurationDifference = videoWatchedDurationDifference;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

}
