
desc "Generate Android App Bundle"
lane :generate_app_file do |signing_config|
  download_file(url: signing_config[:keystore_file_path], destination_path: './app/keystore.jks')
  gradle(
  task: ["bundleRelease", "assembleRelease", "assembleDebug"],
  print_command: false,
  properties: {
    "android.injected.signing.store.file" => "%s/app/keystore.jks"%File.expand_path("..", Dir.pwd),
     "android.injected.signing.store.password" => signing_config[:keystore_password],
     "android.injected.signing.key.alias" => signing_config[:key_alias],
     "android.injected.signing.key.password" => signing_config[:key_password],
     })
end