name: Android CI

on:
  [push]

jobs:
  reuse:
    uses: testpress/android/.github/workflows/setup_project.yml@test_reusable_workflow
    secrets: inherit

  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

