name: Deploy app workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_KEY: 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
      GITHUB_USERNAME: hari-testpress
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install unzip zip
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip sdk-tools-linux-4333796.zip -d Android
          sudo apt-get install -y lib32z1 openjdk-8-jdk
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$PATH:$JAVA_HOME/bin
          printf "\n\nexport JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64\nexport PATH=\$PATH:\$JAVA_HOME/bin" >> ~/.bashrc
          cd Android/tools/bin
          ./sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.2"
          export ANDROID_HOME="$HOME/Android"
          export PATH=$ANDROID_HOME/tools:$PATH
          export PATH=$ANDROID_HOME/tools/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          printf "\n\nexport ANDROID_HOME=\$HOME/Android\nexport PATH=\$PATH:\$ANDROID_HOME/tools\nexport PATH=\$PATH:\$ANDROID_HOME/platform-tools" >> ~/.bashrc
          ./sdkmanager --updatecurl -s "https://get.sdkman.io" | bashsource "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 6.5
          gradle -v
          export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
      
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Caching ruby dependencies
        uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-gems-${{ secrets.GEMS_CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Caching Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies to support ruby project
        run: |
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install

      - name: Build and distribute app
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane deploy