name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: testpress/android/.github/workflows/setup_project.yml@test_reusable_workflow
      with:
        secrets: inherit

