name: Create and Publish Docker Image

on:
  workflow_call:
    secrets:
      GH_ACCESS_KEY:
        required: true
      GH_USERNAME:
        required: true
      API_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      API_ACCESS_KEY: ${{secrets.API_ACCESS_KEY}}

    steps: 
      - name: Test
        run: |
          echo "hello world" 
          echo $API_ACCESS_KEY